import Foundation
import UIKit
import SwiftUI

class ExportService {
    static let shared = ExportService()

    private init() {}

    // MARK: - PDF Export (Professional white background)

    func generatePDF(
        floorPlan: FloorPlan,
        unit: MeasurementUnit,
        showMeasurements: Bool
    ) -> Data {
        let pageWidth: CGFloat = 612 // US Letter
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50

        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        )

        return renderer.pdfData { context in
            context.beginPage()

            // White background
            UIColor.white.setFill()
            UIRectFill(CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

            let drawArea = CGRect(
                x: margin,
                y: margin + 60,
                width: pageWidth - margin * 2,
                height: pageHeight - margin * 2 - 100
            )

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 22, weight: .bold),
                .foregroundColor: UIColor.black
            ]
            (floorPlan.name as NSString).draw(at: CGPoint(x: margin, y: margin), withAttributes: titleAttrs)

            // Date
            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .long
            let dateAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 11, weight: .regular),
                .foregroundColor: UIColor.gray
            ]
            (dateFormatter.string(from: floorPlan.createdAt) as NSString).draw(
                at: CGPoint(x: margin, y: margin + 28),
                withAttributes: dateAttrs
            )

            // Draw floor plan
            drawFloorPlan(
                floorPlan: floorPlan,
                in: drawArea,
                context: UIGraphicsGetCurrentContext()!,
                unit: unit,
                showMeasurements: showMeasurements,
                darkMode: false
            )

            // Total area
            let totalArea = estimateTotalArea(floorPlan)
            if totalArea > 0 {
                let areaText: String
                switch unit {
                case .feet:
                    areaText = String(format: "TOTAL: %.0f sq. ft", totalArea * 10.7639)
                case .meters:
                    areaText = String(format: "TOTAL: %.1f sq. m", totalArea)
                }
                let areaAttrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.monospacedSystemFont(ofSize: 10, weight: .bold),
                    .foregroundColor: UIColor.darkGray
                ]
                let areaSize = (areaText as NSString).size(withAttributes: areaAttrs)
                (areaText as NSString).draw(
                    at: CGPoint(x: (pageWidth - areaSize.width) / 2, y: pageHeight - margin - 20),
                    withAttributes: areaAttrs
                )
            }

            // Footer
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 8, weight: .regular),
                .foregroundColor: UIColor.lightGray
            ]
            ("Generated by Huff Scan" as NSString).draw(
                at: CGPoint(x: margin, y: pageHeight - margin + 10),
                withAttributes: footerAttrs
            )
        }
    }

    // MARK: - JPEG Export (Dark mode)

    func generateJPEG(
        floorPlan: FloorPlan,
        unit: MeasurementUnit,
        showMeasurements: Bool,
        scale: CGFloat = 2.0
    ) -> UIImage? {
        let width: CGFloat = 1200
        let height: CGFloat = 900
        let margin: CGFloat = 60

        let renderer = UIGraphicsImageRenderer(size: CGSize(width: width, height: height))

        return renderer.image { context in
            UIColor(red: 14/255, green: 17/255, blue: 23/255, alpha: 1).setFill()
            context.fill(CGRect(x: 0, y: 0, width: width, height: height))

            let drawArea = CGRect(
                x: margin,
                y: margin + 50,
                width: width - margin * 2,
                height: height - margin * 2 - 70
            )

            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 28, weight: .bold),
                .foregroundColor: UIColor.white
            ]
            (floorPlan.name as NSString).draw(at: CGPoint(x: margin, y: margin), withAttributes: titleAttrs)

            drawFloorPlan(
                floorPlan: floorPlan,
                in: drawArea,
                context: context.cgContext,
                unit: unit,
                showMeasurements: showMeasurements,
                darkMode: true
            )
        }
    }

    // MARK: - Core Drawing (Architectural Style)

    private func drawFloorPlan(
        floorPlan: FloorPlan,
        in rect: CGRect,
        context: CGContext,
        unit: MeasurementUnit,
        showMeasurements: Bool,
        darkMode: Bool
    ) {
        let bounds = floorPlan.boundingRect
        guard bounds.width > 0 && bounds.height > 0 else { return }

        let scaleX = rect.width / bounds.width
        let scaleY = rect.height / bounds.height
        let scale = min(scaleX, scaleY) * 0.80

        let offsetX = rect.midX - bounds.midX * scale
        let offsetY = rect.midY - bounds.midY * scale

        let wallThickness: CGFloat = max(6 * scale, 3.0)

        func transform(_ point: CGPoint) -> CGPoint {
            CGPoint(x: point.x * scale + offsetX, y: point.y * scale + offsetY)
        }

        let wallColor: UIColor = darkMode
            ? UIColor(white: 0.82, alpha: 1)
            : UIColor(red: 0.12, green: 0.12, blue: 0.12, alpha: 1)
        let doorColor: UIColor = darkMode
            ? UIColor(white: 0.6, alpha: 1)
            : UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1)
        let windowColor: UIColor = darkMode
            ? UIColor(red: 0.45, green: 0.73, blue: 1.0, alpha: 1)
            : UIColor(red: 0.45, green: 0.73, blue: 1.0, alpha: 1)
        let measureColor: UIColor = darkMode
            ? UIColor(white: 0.55, alpha: 1)
            : UIColor.darkGray

        // Room label fills
        for label in floorPlan.roomLabels {
            let center = transform(label.position)
            UIColor(Color(hex: label.colorHex)).withAlphaComponent(darkMode ? 0.10 : 0.08).setFill()
            let radius: CGFloat = 40 * scale
            context.fillEllipse(in: CGRect(x: center.x - radius, y: center.y - radius, width: radius * 2, height: radius * 2))
        }

        // Walls as filled rectangles
        for wall in floorPlan.walls {
            let start = transform(wall.start)
            let end = transform(wall.end)
            let angle = atan2(end.y - start.y, end.x - start.x)
            let perpX = -sin(angle) * wallThickness / 2
            let perpY = cos(angle) * wallThickness / 2

            let wallPath = UIBezierPath()
            wallPath.move(to: CGPoint(x: start.x + perpX, y: start.y + perpY))
            wallPath.addLine(to: CGPoint(x: end.x + perpX, y: end.y + perpY))
            wallPath.addLine(to: CGPoint(x: end.x - perpX, y: end.y - perpY))
            wallPath.addLine(to: CGPoint(x: start.x - perpX, y: start.y - perpY))
            wallPath.close()

            wallColor.setFill()
            wallPath.fill()
        }

        // Corner joints
        let threshold: CGFloat = wallThickness * 1.5
        var endpoints: [CGPoint] = []
        for wall in floorPlan.walls {
            endpoints.append(transform(wall.start))
            endpoints.append(transform(wall.end))
        }
        for i in 0..<endpoints.count {
            for j in (i+1)..<endpoints.count {
                let dist = hypot(endpoints[i].x - endpoints[j].x, endpoints[i].y - endpoints[j].y)
                if dist < threshold {
                    let mid = CGPoint(x: (endpoints[i].x + endpoints[j].x) / 2, y: (endpoints[i].y + endpoints[j].y) / 2)
                    let half = wallThickness / 2
                    wallColor.setFill()
                    context.fill(CGRect(x: mid.x - half, y: mid.y - half, width: wallThickness, height: wallThickness))
                }
            }
        }

        // Windows (triple line)
        for window in floorPlan.windows {
            let start = transform(window.start)
            let end = transform(window.end)
            let angle = atan2(end.y - start.y, end.x - start.x)

            // Clear wall behind
            let bg = darkMode ? UIColor(red: 14/255, green: 17/255, blue: 23/255, alpha: 1) : UIColor.white
            let clearPX = -sin(angle) * wallThickness / 2
            let clearPY = cos(angle) * wallThickness / 2
            let clearPath = UIBezierPath()
            clearPath.move(to: CGPoint(x: start.x + clearPX, y: start.y + clearPY))
            clearPath.addLine(to: CGPoint(x: end.x + clearPX, y: end.y + clearPY))
            clearPath.addLine(to: CGPoint(x: end.x - clearPX, y: end.y - clearPY))
            clearPath.addLine(to: CGPoint(x: start.x - clearPX, y: start.y - clearPY))
            clearPath.close()
            bg.setFill()
            clearPath.fill()

            // Triple lines
            context.setStrokeColor(windowColor.cgColor)
            let winOffset = wallThickness * 0.35
            for offset in [-winOffset, 0, winOffset] {
                let px = -sin(angle) * offset
                let py = cos(angle) * offset
                context.setLineWidth(offset == 0 ? 0.8 : 1.2)
                context.move(to: CGPoint(x: start.x + px, y: start.y + py))
                context.addLine(to: CGPoint(x: end.x + px, y: end.y + py))
                context.strokePath()
            }
        }

        // Doors (quarter arc + panel line)
        for door in floorPlan.doors {
            let pos = transform(door.position)
            let arcRadius = door.width * scale / 2

            // Clear wall behind door
            let bg = darkMode ? UIColor(red: 14/255, green: 17/255, blue: 23/255, alpha: 1) : UIColor.white
            let da = door.angle
            let dCos = cos(da) * Double(arcRadius)
            let dSin = sin(da) * Double(arcRadius)
            let pX = -sin(da) * Double(wallThickness) / 2
            let pY = cos(da) * Double(wallThickness) / 2
            let cp = UIBezierPath()
            cp.move(to: CGPoint(x: pos.x + pX - dCos, y: pos.y + pY - dSin))
            cp.addLine(to: CGPoint(x: pos.x + pX + dCos, y: pos.y + pY + dSin))
            cp.addLine(to: CGPoint(x: pos.x - pX + dCos, y: pos.y - pY + dSin))
            cp.addLine(to: CGPoint(x: pos.x - pX - dCos, y: pos.y - pY - dSin))
            cp.close()
            bg.setFill()
            cp.fill()

            // Arc
            context.setStrokeColor(doorColor.cgColor)
            context.setLineWidth(1.5)
            context.addArc(
                center: pos,
                radius: arcRadius,
                startAngle: CGFloat(door.angle) - .pi / 2,
                endAngle: CGFloat(door.angle),
                clockwise: false
            )
            context.strokePath()

            // Door panel line
            context.setLineWidth(2)
            context.move(to: pos)
            context.addLine(to: CGPoint(
                x: pos.x + arcRadius * CGFloat(cos(door.angle)),
                y: pos.y + arcRadius * CGFloat(sin(door.angle))
            ))
            context.strokePath()
        }

        // Wall measurements
        if showMeasurements {
            for wall in floorPlan.walls {
                guard wall.lengthMeters > 0.3 else { continue }
                let start = transform(wall.start)
                let end = transform(wall.end)
                let mid = CGPoint(x: (start.x + end.x) / 2, y: (start.y + end.y) / 2)
                let text = unit.formatted(meters: wall.lengthMeters)
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.monospacedSystemFont(ofSize: 9, weight: .semibold),
                    .foregroundColor: measureColor
                ]
                let angle = atan2(end.y - start.y, end.x - start.x)
                let perpOffset = wallThickness / 2 + 12
                (text as NSString).draw(
                    at: CGPoint(x: mid.x - sin(angle) * perpOffset - 15, y: mid.y + cos(angle) * perpOffset - 6),
                    withAttributes: attrs
                )
            }
        }

        // Room labels
        for label in floorPlan.roomLabels {
            let center = transform(label.position)
            let nameAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 12, weight: .bold),
                .foregroundColor: darkMode ? UIColor.white : UIColor.black
            ]
            let nameSize = (label.name as NSString).size(withAttributes: nameAttrs)
            (label.name as NSString).draw(
                at: CGPoint(x: center.x - nameSize.width / 2, y: center.y - nameSize.height / 2),
                withAttributes: nameAttrs
            )
        }
    }

    private func estimateTotalArea(_ floorPlan: FloorPlan) -> Double {
        let bounds = floorPlan.boundingRect
        let widthMeters = Double(bounds.width) / 100.0
        let heightMeters = Double(bounds.height) / 100.0
        return widthMeters * heightMeters * 0.7
    }
}
