import Foundation
import UIKit
import SwiftUI

class ExportService {
    static let shared = ExportService()

    private init() {}

    // MARK: - PDF Export (CubiCasa-style white background)

    func generatePDF(
        floorPlan: FloorPlan,
        unit: MeasurementUnit,
        showMeasurements: Bool
    ) -> Data {
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50

        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        )

        return renderer.pdfData { context in
            context.beginPage()

            UIColor.white.setFill()
            UIRectFill(CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))

            let drawArea = CGRect(
                x: margin,
                y: margin + 60,
                width: pageWidth - margin * 2,
                height: pageHeight - margin * 2 - 100
            )

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 20, weight: .bold),
                .foregroundColor: UIColor.black
            ]
            (floorPlan.name as NSString).draw(at: CGPoint(x: margin, y: margin), withAttributes: titleAttrs)

            // Date
            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .long
            let dateAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10, weight: .regular),
                .foregroundColor: UIColor.gray
            ]
            (dateFormatter.string(from: floorPlan.createdAt) as NSString).draw(
                at: CGPoint(x: margin, y: margin + 26),
                withAttributes: dateAttrs
            )

            drawFloorPlan(
                floorPlan: floorPlan,
                in: drawArea,
                context: UIGraphicsGetCurrentContext()!,
                unit: unit,
                showMeasurements: showMeasurements,
                darkMode: false
            )

            // Total area
            let totalArea = estimateTotalArea(floorPlan)
            if totalArea > 0 {
                let areaText: String
                switch unit {
                case .feet:
                    areaText = String(format: "TOTAL: %.0f sq. ft", totalArea * 10.7639)
                case .meters:
                    areaText = String(format: "TOTAL: %.1f sq. m", totalArea)
                }
                let areaAttrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.monospacedSystemFont(ofSize: 9, weight: .bold),
                    .foregroundColor: UIColor.darkGray
                ]
                let areaSize = (areaText as NSString).size(withAttributes: areaAttrs)
                (areaText as NSString).draw(
                    at: CGPoint(x: (pageWidth - areaSize.width) / 2, y: pageHeight - margin - 20),
                    withAttributes: areaAttrs
                )
            }

            // Floor label
            let floorAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 9, weight: .regular),
                .foregroundColor: UIColor.gray
            ]
            ("Floor 1" as NSString).draw(at: CGPoint(x: margin, y: pageHeight - margin - 20), withAttributes: floorAttrs)

            // Footer
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 7, weight: .regular),
                .foregroundColor: UIColor.lightGray
            ]
            ("Generated by Huff Scan" as NSString).draw(
                at: CGPoint(x: margin, y: pageHeight - margin + 10),
                withAttributes: footerAttrs
            )
        }
    }

    // MARK: - JPEG Export

    func generateJPEG(
        floorPlan: FloorPlan,
        unit: MeasurementUnit,
        showMeasurements: Bool,
        scale: CGFloat = 2.0
    ) -> UIImage? {
        let width: CGFloat = 1200
        let height: CGFloat = 900
        let margin: CGFloat = 60

        let renderer = UIGraphicsImageRenderer(size: CGSize(width: width, height: height))

        return renderer.image { context in
            UIColor.white.setFill()
            context.fill(CGRect(x: 0, y: 0, width: width, height: height))

            let drawArea = CGRect(
                x: margin,
                y: margin + 50,
                width: width - margin * 2,
                height: height - margin * 2 - 70
            )

            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 24, weight: .bold),
                .foregroundColor: UIColor.black
            ]
            (floorPlan.name as NSString).draw(at: CGPoint(x: margin, y: margin), withAttributes: titleAttrs)

            drawFloorPlan(
                floorPlan: floorPlan,
                in: drawArea,
                context: context.cgContext,
                unit: unit,
                showMeasurements: showMeasurements,
                darkMode: false
            )
        }
    }

    // MARK: - Core Drawing (CubiCasa Architectural Style)

    private func drawFloorPlan(
        floorPlan: FloorPlan,
        in rect: CGRect,
        context: CGContext,
        unit: MeasurementUnit,
        showMeasurements: Bool,
        darkMode: Bool
    ) {
        let bounds = floorPlan.boundingRect
        guard bounds.width > 0 && bounds.height > 0 else { return }

        let scaleX = rect.width / bounds.width
        let scaleY = rect.height / bounds.height
        let scale = min(scaleX, scaleY) * 0.78

        let offsetX = rect.midX - bounds.midX * scale
        let offsetY = rect.midY - bounds.midY * scale

        let wallThickness: CGFloat = max(8 * scale, 4.0)

        func transform(_ point: CGPoint) -> CGPoint {
            CGPoint(x: point.x * scale + offsetX, y: point.y * scale + offsetY)
        }

        let wallColor = UIColor(red: 0.1, green: 0.1, blue: 0.1, alpha: 1)
        let doorColor = UIColor(red: 0.3, green: 0.3, blue: 0.3, alpha: 1)
        let windowColor = UIColor(red: 0.45, green: 0.73, blue: 1.0, alpha: 1)
        let fixtureColor = UIColor(red: 0.35, green: 0.35, blue: 0.35, alpha: 1)
        let measureColor = UIColor(red: 0.4, green: 0.4, blue: 0.4, alpha: 1)
        let bgColor = UIColor.white

        // Walls as filled rectangles
        for wall in floorPlan.walls {
            let start = transform(wall.start)
            let end = transform(wall.end)
            let angle = atan2(end.y - start.y, end.x - start.x)
            let perpX = -sin(angle) * wallThickness / 2
            let perpY = cos(angle) * wallThickness / 2

            let path = UIBezierPath()
            path.move(to: CGPoint(x: start.x + perpX, y: start.y + perpY))
            path.addLine(to: CGPoint(x: end.x + perpX, y: end.y + perpY))
            path.addLine(to: CGPoint(x: end.x - perpX, y: end.y - perpY))
            path.addLine(to: CGPoint(x: start.x - perpX, y: start.y - perpY))
            path.close()
            wallColor.setFill()
            path.fill()
        }

        // Corner joints
        let threshold: CGFloat = wallThickness * 1.5
        var endpoints: [CGPoint] = []
        for wall in floorPlan.walls {
            endpoints.append(transform(wall.start))
            endpoints.append(transform(wall.end))
        }
        for i in 0..<endpoints.count {
            for j in (i+1)..<endpoints.count {
                let dist = hypot(endpoints[i].x - endpoints[j].x, endpoints[i].y - endpoints[j].y)
                if dist < threshold {
                    let mid = CGPoint(x: (endpoints[i].x + endpoints[j].x) / 2, y: (endpoints[i].y + endpoints[j].y) / 2)
                    let half = wallThickness / 2
                    wallColor.setFill()
                    context.fill(CGRect(x: mid.x - half, y: mid.y - half, width: wallThickness, height: wallThickness))
                }
            }
        }

        // Windows
        for window in floorPlan.windows {
            let start = transform(window.start)
            let end = transform(window.end)
            let angle = atan2(end.y - start.y, end.x - start.x)

            // Clear wall
            clearWallGapCG(context: context, start: start, end: end, angle: angle, wallThickness: wallThickness, bgColor: bgColor)

            // Two parallel lines
            context.setStrokeColor(wallColor.cgColor)
            let winOffset = wallThickness * 0.3
            for offset in [-winOffset, winOffset] {
                let px = -sin(angle) * offset
                let py = cos(angle) * offset
                context.setLineWidth(1.2)
                context.move(to: CGPoint(x: start.x + px, y: start.y + py))
                context.addLine(to: CGPoint(x: end.x + px, y: end.y + py))
                context.strokePath()
            }
        }

        // Doors
        for door in floorPlan.doors {
            let pos = transform(door.position)
            let arcRadius = door.width * scale / 2
            let da = door.angle
            let dCos = cos(da) * Double(arcRadius)
            let dSin = sin(da) * Double(arcRadius)
            let s = CGPoint(x: pos.x - dCos, y: pos.y - dSin)
            let e = CGPoint(x: pos.x + dCos, y: pos.y + dSin)
            clearWallGapCG(context: context, start: s, end: e, angle: CGFloat(da), wallThickness: wallThickness, bgColor: bgColor)

            context.setStrokeColor(doorColor.cgColor)
            context.setLineWidth(1.0)
            context.addArc(
                center: pos,
                radius: arcRadius,
                startAngle: CGFloat(door.angle) - .pi / 2,
                endAngle: CGFloat(door.angle),
                clockwise: false
            )
            context.strokePath()

            context.setLineWidth(1.5)
            context.move(to: pos)
            context.addLine(to: CGPoint(
                x: pos.x + arcRadius * CGFloat(cos(door.angle)),
                y: pos.y + arcRadius * CGFloat(sin(door.angle))
            ))
            context.strokePath()
        }

        // Fixtures
        for fixture in floorPlan.fixtures {
            let center = transform(fixture.position)
            let w = max(fixture.size.width * scale, 10)
            let h = max(fixture.size.height * scale, 10)
            let rect = CGRect(x: center.x - w / 2, y: center.y - h / 2, width: w, height: h)

            context.setStrokeColor(fixtureColor.cgColor)
            context.setLineWidth(0.8)

            switch fixture.type {
            case .toilet:
                context.stroke(rect)
                let circleSize = min(w, h) * 0.6
                context.strokeEllipse(in: CGRect(x: center.x - circleSize / 2, y: center.y - circleSize / 2, width: circleSize, height: circleSize))
            case .bathtub:
                let outer = UIBezierPath(roundedRect: rect, cornerRadius: min(w, h) * 0.2)
                context.addPath(outer.cgPath)
                context.strokePath()
                let inner = UIBezierPath(roundedRect: rect.insetBy(dx: 3, dy: 3), cornerRadius: min(w, h) * 0.15)
                context.addPath(inner.cgPath)
                context.strokePath()
            case .sink:
                context.stroke(rect)
                let r = min(w, h) * 0.3
                context.strokeEllipse(in: CGRect(x: center.x - r, y: center.y - r, width: r * 2, height: r * 2))
            case .stove, .oven:
                context.stroke(rect)
                let br = min(w, h) * 0.12
                for (ox, oy) in [(-0.25, -0.25), (0.25, -0.25), (-0.25, 0.25), (0.25, 0.25)] as [(CGFloat, CGFloat)] {
                    context.strokeEllipse(in: CGRect(x: center.x + w * ox - br, y: center.y + h * oy - br, width: br * 2, height: br * 2))
                }
            case .stairs:
                context.stroke(rect)
                let steps = 6
                for i in 1..<steps {
                    let y = rect.minY + rect.height * CGFloat(i) / CGFloat(steps)
                    context.move(to: CGPoint(x: rect.minX, y: y))
                    context.addLine(to: CGPoint(x: rect.maxX, y: y))
                    context.strokePath()
                }
            default:
                context.stroke(rect)
            }
        }

        // Wall measurements
        if showMeasurements {
            for wall in floorPlan.walls {
                guard wall.lengthMeters > 0.3 else { continue }
                let start = transform(wall.start)
                let end = transform(wall.end)
                let mid = CGPoint(x: (start.x + end.x) / 2, y: (start.y + end.y) / 2)
                let angle = atan2(end.y - start.y, end.x - start.x)
                let perpOffset = wallThickness / 2 + 10
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.monospacedSystemFont(ofSize: 7, weight: .medium),
                    .foregroundColor: measureColor
                ]
                let text = unit.formatted(meters: wall.lengthMeters)
                (text as NSString).draw(
                    at: CGPoint(x: mid.x - sin(angle) * perpOffset - 12, y: mid.y + cos(angle) * perpOffset - 5),
                    withAttributes: attrs
                )
            }
        }

        // Room labels
        for label in floorPlan.roomLabels {
            let center = transform(label.position)
            let nameAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 10, weight: .bold),
                .foregroundColor: UIColor.black
            ]
            let nameSize = (label.name as NSString).size(withAttributes: nameAttrs)
            (label.name as NSString).draw(
                at: CGPoint(x: center.x - nameSize.width / 2, y: center.y - nameSize.height / 2),
                withAttributes: nameAttrs
            )
        }
    }

    private func clearWallGapCG(context: CGContext, start: CGPoint, end: CGPoint, angle: CGFloat, wallThickness: CGFloat, bgColor: UIColor) {
        let expand: CGFloat = 1.5
        let perpX = -sin(angle) * wallThickness * expand / 2
        let perpY = cos(angle) * wallThickness * expand / 2
        let path = UIBezierPath()
        path.move(to: CGPoint(x: start.x + perpX, y: start.y + perpY))
        path.addLine(to: CGPoint(x: end.x + perpX, y: end.y + perpY))
        path.addLine(to: CGPoint(x: end.x - perpX, y: end.y - perpY))
        path.addLine(to: CGPoint(x: start.x - perpX, y: start.y - perpY))
        path.close()
        bgColor.setFill()
        path.fill()
    }

    private func estimateTotalArea(_ floorPlan: FloorPlan) -> Double {
        let bounds = floorPlan.boundingRect
        let widthMeters = Double(bounds.width) / 100.0
        let heightMeters = Double(bounds.height) / 100.0
        return widthMeters * heightMeters * 0.7
    }
}
