import Foundation
import UIKit
import SwiftUI

class ExportService {
    static let shared = ExportService()

    private init() {}

    // MARK: - PDF Export

    func generatePDF(
        floorPlan: FloorPlan,
        unit: MeasurementUnit,
        showMeasurements: Bool
    ) -> Data {
        let pageWidth: CGFloat = 612 // US Letter
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50

        let renderer = UIGraphicsPDFRenderer(
            bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        )

        return renderer.pdfData { context in
            context.beginPage()

            let drawArea = CGRect(
                x: margin,
                y: margin + 60,
                width: pageWidth - margin * 2,
                height: pageHeight - margin * 2 - 80
            )

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 24, weight: .bold),
                .foregroundColor: UIColor.black
            ]
            let title = floorPlan.name as NSString
            title.draw(at: CGPoint(x: margin, y: margin), withAttributes: titleAttrs)

            // Date
            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .long
            let dateAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 12, weight: .regular),
                .foregroundColor: UIColor.darkGray
            ]
            let dateStr = dateFormatter.string(from: floorPlan.createdAt) as NSString
            dateStr.draw(at: CGPoint(x: margin, y: margin + 32), withAttributes: dateAttrs)

            // Draw floor plan
            drawFloorPlan(
                floorPlan: floorPlan,
                in: drawArea,
                context: UIGraphicsGetCurrentContext()!,
                unit: unit,
                showMeasurements: showMeasurements,
                darkMode: false
            )

            // Footer
            let footerAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 9, weight: .regular),
                .foregroundColor: UIColor.gray
            ]
            let footer = "Generated by Huff Scan" as NSString
            footer.draw(
                at: CGPoint(x: margin, y: pageHeight - margin + 10),
                withAttributes: footerAttrs
            )
        }
    }

    // MARK: - JPEG Export

    func generateJPEG(
        floorPlan: FloorPlan,
        unit: MeasurementUnit,
        showMeasurements: Bool,
        scale: CGFloat = 2.0
    ) -> UIImage? {
        let width: CGFloat = 1200
        let height: CGFloat = 900
        let margin: CGFloat = 60

        let renderer = UIGraphicsImageRenderer(
            size: CGSize(width: width, height: height)
        )

        let image = renderer.image { context in
            // Background
            UIColor(red: 14/255, green: 17/255, blue: 23/255, alpha: 1).setFill()
            context.fill(CGRect(x: 0, y: 0, width: width, height: height))

            let drawArea = CGRect(
                x: margin,
                y: margin + 50,
                width: width - margin * 2,
                height: height - margin * 2 - 70
            )

            // Title
            let titleAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 28, weight: .bold),
                .foregroundColor: UIColor.white
            ]
            (floorPlan.name as NSString).draw(
                at: CGPoint(x: margin, y: margin),
                withAttributes: titleAttrs
            )

            // Draw floor plan
            drawFloorPlan(
                floorPlan: floorPlan,
                in: drawArea,
                context: context.cgContext,
                unit: unit,
                showMeasurements: showMeasurements,
                darkMode: true
            )
        }

        return image
    }

    // MARK: - Core Drawing

    private func drawFloorPlan(
        floorPlan: FloorPlan,
        in rect: CGRect,
        context: CGContext,
        unit: MeasurementUnit,
        showMeasurements: Bool,
        darkMode: Bool
    ) {
        let bounds = floorPlan.boundingRect
        guard bounds.width > 0 && bounds.height > 0 else { return }

        let scaleX = rect.width / bounds.width
        let scaleY = rect.height / bounds.height
        let scale = min(scaleX, scaleY) * 0.85

        let offsetX = rect.midX - bounds.midX * scale
        let offsetY = rect.midY - bounds.midY * scale

        func transform(_ point: CGPoint) -> CGPoint {
            CGPoint(x: point.x * scale + offsetX, y: point.y * scale + offsetY)
        }

        let wallColor = darkMode
            ? UIColor(red: 0.75, green: 0.8, blue: 0.85, alpha: 1)
            : UIColor(red: 0.17, green: 0.24, blue: 0.31, alpha: 1)
        let doorColor = UIColor(red: 0.55, green: 0.45, blue: 0.33, alpha: 1)
        let windowColor = UIColor(red: 0.45, green: 0.73, blue: 1.0, alpha: 1)
        let measureColor = darkMode
            ? UIColor(red: 0.58, green: 0.65, blue: 0.7, alpha: 1)
            : UIColor.darkGray

        // Draw room label fills
        for label in floorPlan.roomLabels {
            let center = transform(label.position)
            let fillColor = UIColor(Color(hex: label.colorHex)).withAlphaComponent(0.12)
            fillColor.setFill()
            let radius: CGFloat = 40 * scale
            let ellipseRect = CGRect(x: center.x - radius, y: center.y - radius, width: radius * 2, height: radius * 2)
            context.fillEllipse(in: ellipseRect)
        }

        // Draw walls
        context.setLineCap(.round)
        for wall in floorPlan.walls {
            let start = transform(wall.start)
            let end = transform(wall.end)
            let thickness = max(wall.thickness * scale, 2.0)

            context.setStrokeColor(wallColor.cgColor)
            context.setLineWidth(thickness)
            context.move(to: start)
            context.addLine(to: end)
            context.strokePath()

            if showMeasurements && wall.lengthMeters > 0.3 {
                let mid = CGPoint(x: (start.x + end.x) / 2, y: (start.y + end.y) / 2)
                let text = unit.formatted(meters: wall.lengthMeters)
                let attrs: [NSAttributedString.Key: Any] = [
                    .font: UIFont.monospacedSystemFont(ofSize: 8, weight: .medium),
                    .foregroundColor: measureColor
                ]
                let angle = atan2(end.y - start.y, end.x - start.x)
                let perpX = -sin(angle) * 10
                let perpY = cos(angle) * 10
                (text as NSString).draw(
                    at: CGPoint(x: mid.x + perpX - 15, y: mid.y + perpY - 5),
                    withAttributes: attrs
                )
            }
        }

        // Draw windows
        for window in floorPlan.windows {
            let start = transform(window.start)
            let end = transform(window.end)

            context.setStrokeColor(windowColor.cgColor)
            context.setLineWidth(3 * scale)
            context.setLineDash(phase: 0, lengths: [6, 4])
            context.move(to: start)
            context.addLine(to: end)
            context.strokePath()
            context.setLineDash(phase: 0, lengths: [])
        }

        // Draw doors
        for door in floorPlan.doors {
            let pos = transform(door.position)
            let arcRadius = door.width * scale / 2

            context.setStrokeColor(doorColor.cgColor)
            context.setLineWidth(1.5)
            context.addArc(
                center: pos,
                radius: arcRadius,
                startAngle: CGFloat(door.angle),
                endAngle: CGFloat(door.angle) + .pi / 2,
                clockwise: false
            )
            context.strokePath()
        }

        // Draw room labels
        for label in floorPlan.roomLabels {
            let center = transform(label.position)
            let labelAttrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 11, weight: .semibold),
                .foregroundColor: darkMode ? UIColor.white : UIColor.black
            ]
            let size = (label.name as NSString).size(withAttributes: labelAttrs)
            let bgRect = CGRect(
                x: center.x - size.width / 2 - 6,
                y: center.y - size.height / 2 - 3,
                width: size.width + 12,
                height: size.height + 6
            )
            UIColor(Color(hex: label.colorHex)).withAlphaComponent(0.25).setFill()
            UIBezierPath(roundedRect: bgRect, cornerRadius: 4).fill()

            (label.name as NSString).draw(
                at: CGPoint(x: center.x - size.width / 2, y: center.y - size.height / 2),
                withAttributes: labelAttrs
            )
        }
    }
}
